# Generated by Django 4.2.5 on 2023-09-23 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("todo", "0003_alter_todotask_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todotask",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="todo.user"
            ),
        ),
    ]
